image: python:3
<<<<<<< HEAD
#lint:
#  stage: test
#  script:
#    - pip install yapf==0.32.0
#    - yapf --style google --recursive --diff .
#  only:
#    - merge_requests
=======
<<<<<<< HEAD
=======
#Removed lint because of bug error
>>>>>>> enriquebranch
>>>>>>> ab5dcbb202b0fde44a6c2732f3d3494816325e7c

unittest:
 stage: test
 script:
  - pip install -r requirements.txt
  - pytest .
 only:
  - merge_requests

prod:
 image: google/cloud-sdk:alpine
 stage: deploy
 environment: Production
 only:
  - main
 script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $PROJECT_ID app deploy
